name: CI/CD Front

on:
  push:
    branches:
      - pruevas_devops

env:
  VERCEL_ORG_ID: ${{ secrets.orgId }}
  VERCEL_PROJECT_ID: ${{ secrets.projectId }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v4

      - name: Install Nodejs
        uses: actions/setup-node@v4

      - name: Install dependencias Nodejs
        run: npm install

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.token }}

      - name: Build Project
        run: vercel build --token=${{ secrets.token }}

      - name: Deploy to Vercel (Production)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.token }}
